### ISSUE TITLE
Migration to xenial as default for atlantis (appflow.py)

### ISSUE THREAD

**Issue by ivomarino** [ttssdev/appflow#107]
The new default image for `atlantis` will be `Vagrant-Boxes/xenial64.box`, this issue will help in the migration process. For now we have:

```
brew install python3
pip3 install -r requirements.txt
cd ~/appflow
git checkout 89-appflow-python
vagrant destroy atlantis
vagrant box remove atlantis
ssh-keygen -R atlantis
make vagrant
vagrant up atlantis
vagrant ssh atlantis -c "sudo apt-get install -y python"
# For Mysql
vagrant ssh atlantis -c 'wget https://repo.percona.com/apt/percona-release_0.1-4.$(lsb_release -sc)_all.deb'
vagrant ssh atlantis -c 'dpkg -i percona-release_0.1-4.$(lsb_release -sc)_all.deb'
vagrant ssh atlantis -c 'sudo dpkg -i percona-release_0.1-4.$(lsb_release -sc)_all.deb'
vagrant ssh atlantis -c "sudo apt update; sudo apt upgrade -y"
vagrant ssh atlantis -c "sudo apt-get install -y percona-xtradb-cluster-server-5.7"
vagrant ssh atlantis -c "sudo chown mysql:mysql /run/mysqld"

# note: get ssh pwd for ubuntu user:
vagrant ssh atlantis -c "echo $(cat ~/.ssh/id_rsa.pub) | sudo tee /home/ubuntu/.ssh/authorized_keys"
vagrant ssh atlantis -c "sudo passwd ubuntu" <-- choose your password to use for first provision

# old-alternative: appflow vagrant provision atlantis
./appflow.py provision sp development limit=atlantis firstrun=true tags=shell-users,sudo
./appflow.py provision sp development limit=atlantis
```

from that point on we can access via normal `ssh`.

We should be able to fallback to `trusty` specifying a `Vagrantfile.local.yml`:

```
cat ~/appflow/Vagrantfile.local.yml

synced_folder:
  appflow_folder: "~/Documents/webdev/appflow"
  webdev_folder: "~/Documents/webdev/development"

vm:
  hostname: "atlantis"
  box_url: "Vagrant-Boxes/trusty64.box"
```

MySQL 5.6 -> 5.7

```
not supported in 5.7:

key_buffer
thread_concurrency
```
